language: scala
scala:
  - 2.10.3
  - 2.10.2
  - 2.10.1
  - 2.10.0
  - 2.11.0
jdk:
  - oraclejdk7
  - openjdk7
branches:
  only:
    - master
before_install:
  - 'echo $JAVA_OPTS'
  - 'export JAVA_OPTS="-XX:MaxPermSize=512m -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m"' 
  - chmod +x ./gradlew
install:
  - TERM=dumb ./gradlew assemble
before_script:
  - 'echo $JAVA_OPTS'
  - 'export JAVA_OPTS="-XX:MaxPermSize=512m -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m"'
script:
  - TERM=dumb ./gradlew check
