language: scala
scala:
  - 2.10.2
  - 2.10.1
  - 2.10.0
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
branches:
  only:
    - master
before_install:
  - chmod +x ./gradlew
script:
  - ./gradlew -i check
