language: scala
scala:
  - 2.10.3
  - 2.10.2
  - 2.10.1
  - 2.10.0
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
branches:
  only:
    - master
before_install:
  - chmod +x ./gradlew
install:
  - TERM=dumb ./gradlew assemble
script:
  - TERM=dumb ./gradlew check
